name: Push
on:
  push:
    tags:
      - 'v*'

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: 'write'
      contents: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v6'
        with:
          fetch-depth: 0 # required to fetch all history for all branches and tags

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Docker Build & Push'
        run: |
          make docker-buildx

      - name: 'Setup Flux CLI'
        uses: fluxcd/flux2/action@main

      - name: 'Flux Build & Push'
        run: |
          make flux-push

      - name: 'Flux Tag Latest'
        run: |
          make flux-tag-latest

      - name: 'Build Installer'
        run: |
          make build-installer

      - name: 'Create Release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes \
              dist/install.yaml
